export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';

export const SET_FILTER_PARAMS = 'SET_FILTER_PARAMS';
export const CLEAR_FILTER_PARAMS = 'CLEAR_FILTER_PARAMS';
export const TOGGLE_FILTER_OPTIONS_SECTION = 'SHOW_FILTER_OPTIONS_SECTION';

export const SET_SORT_PARAMS = 'SET_SORT_PARAMS';
export const CLEAR_SORT_PARAMS = 'CLEAR_SORT_PARAMS';
export const TOGGLE_SORT_OPTIONS_SECTION = 'SHOW_SORT_OPTIONS_SECTION';

export const APPLY_FILTER_OPTIONS = 'APPLY_FILTER_OPTIONS';
export const APPLY_SORT_OPTIONS = 'APPLY_SORT_OPTIONS';
